### ISSUE TITLE
何时开源代码

### ISSUE THREAD

**Issue by chenjiachengzzz** [xindongzhang/ELAN#2]
作者您好，您什么能够开源代码！

**Comment by NeonLeexiang** [comment]
你可以看看作者Readme里说的 `SimpleIR` https://github.com/xindongzhang/SimpleIR  那个仓库

**Comment by chenjiachengzzz** [comment]
> 你可以看看作者Readme里说的 `SimpleIR` https://github.com/xindongzhang/SimpleIR 那个仓库

好哒好哒，感谢提醒！
