### ISSUE TITLE
Thank you for your excellent work

### ISSUE THREAD

**Issue by songzijiang** [xindongzhang/ELAN#6]
I am reproducing your scores in your paper, and all looks well. Your framework is the neatest one I have seen. Anyway, thank you.

**Comment by RebornForPower** [comment]
好兄弟 ，你是认真的吗？我拿他代码跑不出对应的结果，而且训练的过程中loss值很大，你确定你自己复现能达到他的结果？

**Comment by RebornForPower** [comment]
are you serious man？
I cannot get the baseline in his paper by his code. The loss in the training stage is so large...
![image](https://user-images.githubusercontent.com/23008582/191536712-b165a11a-6a85-42cc-8419-f68f35bfd60f.png)

**Comment by songzijiang** [comment]
> 

复现出来了啊，大多数指标和论文里一直，一部分指标有略微不同。项目中的PSNR函数是有问题，算出来的指标会偏高。我用的是自己的计算PSNR的函数进行计算的，最后结果和论文中的数据基本一致。

**Comment by RebornForPower** [comment]
> > 
> 
> 复现出来了啊，大多数指标和论文里一直，一部分指标有略微不同。项目中的PSNR函数是有问题，算出来的指标会偏高。我用的是自己的计算PSNR的函数进行计算的，最后结果和论文中的数据基本一致。

感谢答复，还想请教一下你当时复现模型时batchsize调多大，原论文说的是bs=32且输入为64X64的图像，那么就是说，如果做X2的超分，那么输入tensor为(B, C, H, W) = （32,3,64,64），其次原论文说的是用一块2080TI做的实验。
但我自己做的时候发现，我用比2080Ti更大显存的3080Ti跑他的代码的时候，直接OOM（爆显存），所以是我哪里不对吗？
期待您的答复~
